/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    CardSkeleton: typeof import('./src/components/CardSkeleton.vue')['default']
    Chip: typeof import('primevue/chip')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    ExpenseDetail: typeof import('./src/components/expenses/ExpenseDetail.vue')['default']
    ExpenseDrawer: typeof import('./src/components/expenses/ExpenseDrawer.vue')['default']
    ExpenseForm: typeof import('./src/components/expenses/ExpenseForm.vue')['default']
    ExpensePreview: typeof import('./src/components/previews/ExpensePreview.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    GroupDialog: typeof import('./src/components/groups/GroupDialog.vue')['default']
    GroupForm: typeof import('./src/components/groups/GroupForm.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MovementPreview: typeof import('./src/components/previews/MovementPreview.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    PaymentDrawer: typeof import('./src/components/payments/PaymentDrawer.vue')['default']
    PaymentForm: typeof import('./src/components/payments/PaymentForm.vue')['default']
    PaymentPreview: typeof import('./src/components/previews/PaymentPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
